[package]
name = "shop"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inquire = "0.3.0"
rpassword = "7.0.0"
serde_json = { version = "1.0.25"}
serde = {version = "1.0", features = ["derive"]}